/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';

import {
  MatchResults,
} from '@stencil/router';

declare global {

  namespace StencilComponents {
    interface AppHome {

    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppNavbar {

    }
  }

  interface HTMLAppNavbarElement extends StencilComponents.AppNavbar, HTMLStencilElement {}

  var HTMLAppNavbarElement: {
    prototype: HTMLAppNavbarElement;
    new (): HTMLAppNavbarElement;
  };
  interface HTMLElementTagNameMap {
    'app-navbar': HTMLAppNavbarElement;
  }
  interface ElementTagNameMap {
    'app-navbar': HTMLAppNavbarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-navbar': JSXElements.AppNavbarAttributes;
    }
  }
  namespace JSXElements {
    export interface AppNavbarAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppProfile {
      'match': MatchResults;
    }
  }

  interface HTMLAppProfileElement extends StencilComponents.AppProfile, HTMLStencilElement {}

  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  interface ElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-profile': JSXElements.AppProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface AppProfileAttributes extends HTMLAttributes {
      'match'?: MatchResults;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface DtdlApp {

    }
  }

  interface HTMLDtdlAppElement extends StencilComponents.DtdlApp, HTMLStencilElement {}

  var HTMLDtdlAppElement: {
    prototype: HTMLDtdlAppElement;
    new (): HTMLDtdlAppElement;
  };
  interface HTMLElementTagNameMap {
    'dtdl-app': HTMLDtdlAppElement;
  }
  interface ElementTagNameMap {
    'dtdl-app': HTMLDtdlAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'dtdl-app': JSXElements.DtdlAppAttributes;
    }
  }
  namespace JSXElements {
    export interface DtdlAppAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
